# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1107243db5a2aeb413f9fec6b57c86e5e784c877da7118adc0ba2613f6940a8b7dd8aafeabc7f3a135e316dd5ff2904cab7b07b8128e00af06225bc6b8c1ed97

test:
  secret_key_base: 908f14ee8135247533c5a667d819385be611394e68f7a94054df5c814778097d292385bc48ffc754e88849e2a3bcaedd2092513e1ec8b113c2be30a3a92e7335

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
